#!/bin/sh

usage(){
	echo >&2 "Usage: $0 [-n] [install-{all,make,runtime}|uninstall|make]"
	exit 2
}

install_make(){
	make $dry_n install
}

install_runtime(){
	# --dry-run --no-g --no-t --no-p
	rsync -auF -iP --delete \
		--exclude=testdir \
		--exclude=Makefile \
		--exclude='*CMake*' \
		--exclude='README*' \
		--exclude='tags' \
		--exclude='syntax/vim/' \
		runtime/ \
		/usr/local/share/nvim/runtime/ \
                $dry_n

        # exclude tags & syntax/vim(/generated.vim) - generated by make

	# from rip's version:
	# --chown=root:root \
}

maybe_dry(){
  if $dry
  then echo "$@"
  else "$@"
  fi
}

dry=false
dry_n=
if test "$1" = -n
then
  dry=true
  dry_n=-n
  shift
fi

if test $# -ne 1
then usage
fi

case "$1" in
	make)
		WARN_LOG_LEVEL=3
		#make CMAKE_BUILD_TYPE=RelWithDebInfo CMAKE_EXTRA_FLAGS="-DMIN_LOG_LEVEL=$WARN_LOG_LEVEL"
		make $dry_n CMAKE_BUILD_TYPE=Debug CMAKE_EXTRA_FLAGS="-DMIN_LOG_LEVEL=$WARN_LOG_LEVEL"

		# confirm no writes to `.cache/nvim/log` with `strace -e file -o strace-file ./build/bin/nvim`
		;;

	install-all)
		install_make
		install_runtime
		;;

	install-make)
		install_make
		;;

	install-runtime)
		install_runtime
		;;

	uninstall)
		# directories + files:
		#   /usr/local/bin/nvim
		#
		#   /usr/local/share/locale/*/LC_MESSAGES/nvim.mo
		#
		#   /usr/local/share/applications/nvim.desktop
		#   /usr/local/share/pixmaps/nvim.png
		#
		#   /usr/local/share/nvim/
		#
		#   /usr/local/share/man/man1/nvim.1

		maybe_dry rm -f /usr/local/bin/nvim
		maybe_dry rm -fr /usr/local/share/nvim/

		maybe_dry rm -f /usr/local/share/locale/*/LC_MESSAGES/nvim.mo

		maybe_dry rm -f /usr/local/share/applications/nvim.desktop
		maybe_dry rm -f /usr/local/share/pixmaps/nvim.png

		maybe_dry rm -f /usr/local/share/man/man1/nvim.1
		;;

	*)
		usage
		;;
esac
